name: Tests

on:
  pull_request:
  push:
    branches:
      - main

# One active job per PR, cancel older ones on push
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Build and Test
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Gazelle
        run: bazelisk run //:gazelle && git diff --exit-code
      - name: Build and Test
        run: bazelisk test //...
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: bazel-testlogs
          path: bazel-testlogs
